env: &env
    docker:
      - image: satoshikumano/ubuntu-18.04-cpp:0.0.1
version: 2
jobs:
  build:
    <<: *env
    steps:
      - checkout
      - run:
          name: submodule
          command: |
            git submodule init
            git submodule update
      - run:
          name: make build
          command: make build
      - store_artifacts:
          path: kii/libkiisdk.so
          destination: libkiisdk.so
      - run:
          name: make doc
          command: make doc
      - store_artifacts:
          path: kii/html
          destination: html
      - persist_to_workspace:
          root: .
          paths: kii/html
  ltest:
    <<: *env
    steps:
      - checkout
      - run:
          name: submodule
          command: |
            git submodule init
            git submodule update
      - run:
          name: large test
          command: MEMCHECK=1 JUNIT=1 make large-test
      - store_test_results:
          path: tests/large-test/test-results

  deployment:
    <<: *env
    steps:
      - attach_workspace:
          at: kii/html
      - run:
          command: |
      - git clone https://$GH_TOKEN_FOR_HTTPS@github.com/KiiPlatform/KiiThingSDK-Embedded.git
      - cd KiiThingSDK-Embedded && git checkout gh-pages && git config user.email 'satoshi.kumano@kii.com' && git config user.name 'satoshi kumano'
      - rm -rf KiiThingSDK-Embedded/api-doc && mkdir -p KiiThingSDK-Embedded/api-doc
      - cp -r kii/html/ KiiThingSDK-Embedded/api-doc
      - cd KiiThingSDK-Embedded && git add api-doc && git commit -m 'updated doc' && git push origin gh-pages

workflows:
  version: 2
  default:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - ltest:
          requires:
            - build
          filters:
            branches:
              ignore:
                - gh-pages
      - deployment:
          requires:
            - ltest
          filters:
            branches:
              only: master
            tags:
              only: /v[0-9]+(\.[0-9]+){0,2}([-+].+)?/

# vim: set sts=2 sw=2 et:

